// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2648.robot2017.commands;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.GenericHID.RumbleType;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2648.robot2017.Robot;

public class ArcadeDrive extends Command {
//basic frame of a command
    public ArcadeDrive() {
    		//put in whatever subsystem this command uses
        requires(Robot.driveTrain);
    }

    
    protected void initialize() {
    	
    }
    //this is run on every update of the command.
    protected void execute() {
    	Robot.driveTrain.arcadeDrive();
    	System.out.println(Robot.driveTrain.getlEnc().getDistance());
    	if(DriverStation.getInstance().getMatchTime()<10){
    		//Robot.oi.getj1().setRumble(RumbleType.kRightRumble, 1);
    	}
    	System.out.println(Robot.driveTrain.getGyro().getAngle());
    }
    
   //returns if the command is done or not.
    protected boolean isFinished() {
        return false;
    }
    //this is run when the command isfinished.
    protected void end() {
    }

    protected void interrupted() {
    }
}
