// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2648.robot2017.subsystems;

import org.usfirst.frc2648.robot2017.RobotMap;
import org.usfirst.frc2648.robot2017.commands.ShooterStop;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shooter extends Subsystem {

    private final CANTalon lShooter = RobotMap.shooterlShooter;
    private final Encoder encShooter = RobotMap.shooterencShooter;
    private final CANTalon rShooter = RobotMap.shooterrShooter;

    public void initDefaultCommand() {
       setDefaultCommand(new ShooterStop());
    }
    
    public void spin(double speed){
    	lShooter.set(-speed);
    	rShooter.set(speed);
    }
    
    public void stop(){
    	spin(0);
    }
    
    public Encoder getShooterEnc(){
    	return encShooter;
    }
}

